//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Observable.Resources; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ValidationResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ValidationResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Observable.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; est obligatoire..
    /// </summary>
    public static string FieldXIsRequiredError {
        get {
            return ResourceManager.GetString("FieldXIsRequiredError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne correspond pas à un chemin de fichier valide..
    /// </summary>
    public static string FieldXMustBeAnValidFilePathError {
        get {
            return ResourceManager.GetString("FieldXMustBeAnValidFilePathError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être compris entre {1} et {2}..
    /// </summary>
    public static string FieldXMustBeBetweenYAndZError {
        get {
            return ResourceManager.GetString("FieldXMustBeBetweenYAndZError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to La collection &quot;{0}&quot; doit contenir au moins 1 élément..
    /// </summary>
    public static string FieldXMustBeContainOneItemAtLeastError {
        get {
            return ResourceManager.GetString("FieldXMustBeContainOneItemAtLeastError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être dans le passé..
    /// </summary>
    public static string FieldXMustBeInPastError {
        get {
            return ResourceManager.GetString("FieldXMustBeInPastError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être inférieur ou égal à {1}..
    /// </summary>
    public static string FieldXMustBeLowerOrEqualsThanYError {
        get {
            return ResourceManager.GetString("FieldXMustBeLowerOrEqualsThanYError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être inférieur à {1}..
    /// </summary>
    public static string FieldXMustBeLowerThanYError {
        get {
            return ResourceManager.GetString("FieldXMustBeLowerThanYError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être supérieur ou égal à {1}..
    /// </summary>
    public static string FieldXMustBeUpperOrEqualsThanYError {
        get {
            return ResourceManager.GetString("FieldXMustBeUpperOrEqualsThanYError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être supérieur à {1}..
    /// </summary>
    public static string FieldXMustBeUpperThanYError {
        get {
            return ResourceManager.GetString("FieldXMustBeUpperThanYError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne correspond pas à une adresse de messagerie valide..
    /// </summary>
    public static string FieldXMustBeValidEmailAddressError {
        get {
            return ResourceManager.GetString("FieldXMustBeValidEmailAddressError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne correspond pas à un numéro de téléphone valide..
    /// </summary>
    public static string FieldXMustBeValidPhoneNumberError {
        get {
            return ResourceManager.GetString("FieldXMustBeValidPhoneNumberError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Impossible de trouver une partie du chemin &quot;{0}&quot;..
    /// </summary>
    public static string FieldXMustContainExistingFolderError {
        get {
            return ResourceManager.GetString("FieldXMustContainExistingFolderError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le fichier spécifié dans le champ &quot;{0}&quot; n&apos;a pas été trouvé..
    /// </summary>
    public static string FieldXMustContainsExistingFileError {
        get {
            return ResourceManager.GetString("FieldXMustContainsExistingFileError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne doit pas dépasser {1} caractères..
    /// </summary>
    public static string FieldXMustHaveMaxLengthYError {
        get {
            return ResourceManager.GetString("FieldXMustHaveMaxLengthYError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to La collection &quot;{0}&quot; ne doit pas avoir d&apos;élément identique..
    /// </summary>
    public static string FieldXMustHaveUniqueItemsError {
        get {
            return ResourceManager.GetString("FieldXMustHaveUniqueItemsError", resourceCulture);
        }
    }
}
