//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Humanizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DateHumanizeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateHumanizeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Humanizer.Resources.DateHumanizeResources", typeof(DateHumanizeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # jour.
        /// </summary>
        public static string DateTimeFutureDay {
            get {
                return ResourceManager.GetString("DateTimeFutureDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # jours.
        /// </summary>
        public static string DateTimeFutureDayPlural {
            get {
                return ResourceManager.GetString("DateTimeFutureDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # heure.
        /// </summary>
        public static string DateTimeFutureHour {
            get {
                return ResourceManager.GetString("DateTimeFutureHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # heures.
        /// </summary>
        public static string DateTimeFutureHourPlural {
            get {
                return ResourceManager.GetString("DateTimeFutureHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # milliseconde.
        /// </summary>
        public static string DateTimeFutureMillisecond {
            get {
                return ResourceManager.GetString("DateTimeFutureMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans #  millisecondes.
        /// </summary>
        public static string DateTimeFutureMillisecondPlural {
            get {
                return ResourceManager.GetString("DateTimeFutureMillisecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # minute.
        /// </summary>
        public static string DateTimeFutureMinute {
            get {
                return ResourceManager.GetString("DateTimeFutureMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # minutes.
        /// </summary>
        public static string DateTimeFutureMinutePlural {
            get {
                return ResourceManager.GetString("DateTimeFutureMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # mois.
        /// </summary>
        public static string DateTimeFutureMonth {
            get {
                return ResourceManager.GetString("DateTimeFutureMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # mois.
        /// </summary>
        public static string DateTimeFutureMonthPlural {
            get {
                return ResourceManager.GetString("DateTimeFutureMonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # seconde.
        /// </summary>
        public static string DateTimeFutureSecond {
            get {
                return ResourceManager.GetString("DateTimeFutureSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # secondes.
        /// </summary>
        public static string DateTimeFutureSecondPlural {
            get {
                return ResourceManager.GetString("DateTimeFutureSecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # semaine.
        /// </summary>
        public static string DateTimeFutureWeek {
            get {
                return ResourceManager.GetString("DateTimeFutureWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # semaines.
        /// </summary>
        public static string DateTimeFutureWeekPlural {
            get {
                return ResourceManager.GetString("DateTimeFutureWeekPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # an.
        /// </summary>
        public static string DateTimeFutureYear {
            get {
                return ResourceManager.GetString("DateTimeFutureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans # ans.
        /// </summary>
        public static string DateTimeFutureYearPlural {
            get {
                return ResourceManager.GetString("DateTimeFutureYearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jamais.
        /// </summary>
        public static string DateTimeNever {
            get {
                return ResourceManager.GetString("DateTimeNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenant.
        /// </summary>
        public static string DateTimeNow {
            get {
                return ResourceManager.GetString("DateTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier.
        /// </summary>
        public static string DateTimePastDay {
            get {
                return ResourceManager.GetString("DateTimePastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # jours.
        /// </summary>
        public static string DateTimePastDayPlural {
            get {
                return ResourceManager.GetString("DateTimePastDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # heure.
        /// </summary>
        public static string DateTimePastHour {
            get {
                return ResourceManager.GetString("DateTimePastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # heures.
        /// </summary>
        public static string DateTimePastHourPlural {
            get {
                return ResourceManager.GetString("DateTimePastHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # milliseconde.
        /// </summary>
        public static string DateTimePastMillisecond {
            get {
                return ResourceManager.GetString("DateTimePastMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # millisecondes.
        /// </summary>
        public static string DateTimePastMillisecondPlural {
            get {
                return ResourceManager.GetString("DateTimePastMillisecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # minute.
        /// </summary>
        public static string DateTimePastMinute {
            get {
                return ResourceManager.GetString("DateTimePastMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # minutes.
        /// </summary>
        public static string DateTimePastMinutePlural {
            get {
                return ResourceManager.GetString("DateTimePastMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # mois.
        /// </summary>
        public static string DateTimePastMonth {
            get {
                return ResourceManager.GetString("DateTimePastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # mois.
        /// </summary>
        public static string DateTimePastMonthPlural {
            get {
                return ResourceManager.GetString("DateTimePastMonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # seconde.
        /// </summary>
        public static string DateTimePastSecond {
            get {
                return ResourceManager.GetString("DateTimePastSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # secondes.
        /// </summary>
        public static string DateTimePastSecondPlural {
            get {
                return ResourceManager.GetString("DateTimePastSecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # semaine.
        /// </summary>
        public static string DateTimePastWeek {
            get {
                return ResourceManager.GetString("DateTimePastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # semaines.
        /// </summary>
        public static string DateTimePastWeekPlural {
            get {
                return ResourceManager.GetString("DateTimePastWeekPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # an.
        /// </summary>
        public static string DateTimePastYear {
            get {
                return ResourceManager.GetString("DateTimePastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il y a # ans.
        /// </summary>
        public static string DateTimePastYearPlural {
            get {
                return ResourceManager.GetString("DateTimePastYearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to demain.
        /// </summary>
        public static string DateTimeTomorrow {
            get {
                return ResourceManager.GetString("DateTimeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier.
        /// </summary>
        public static string DateTimeYesterday {
            get {
                return ResourceManager.GetString("DateTimeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pas de temps.
        /// </summary>
        public static string DateTimeZero {
            get {
                return ResourceManager.GetString("DateTimeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # jour.
        /// </summary>
        public static string TimeSpanDay {
            get {
                return ResourceManager.GetString("TimeSpanDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # jours.
        /// </summary>
        public static string TimeSpanDayPlural {
            get {
                return ResourceManager.GetString("TimeSpanDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 jour.
        /// </summary>
        public static string TimeSpanDayZero {
            get {
                return ResourceManager.GetString("TimeSpanDayZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # heure.
        /// </summary>
        public static string TimeSpanHour {
            get {
                return ResourceManager.GetString("TimeSpanHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # heures.
        /// </summary>
        public static string TimeSpanHourPlural {
            get {
                return ResourceManager.GetString("TimeSpanHourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 heure.
        /// </summary>
        public static string TimeSpanHourZero {
            get {
                return ResourceManager.GetString("TimeSpanHourZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # milliseconde.
        /// </summary>
        public static string TimeSpanMillisecond {
            get {
                return ResourceManager.GetString("TimeSpanMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # millisecondes.
        /// </summary>
        public static string TimeSpanMillisecondPlural {
            get {
                return ResourceManager.GetString("TimeSpanMillisecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 milliseconde.
        /// </summary>
        public static string TimeSpanMillisecondZero {
            get {
                return ResourceManager.GetString("TimeSpanMillisecondZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # minute.
        /// </summary>
        public static string TimeSpanMinute {
            get {
                return ResourceManager.GetString("TimeSpanMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # minutes.
        /// </summary>
        public static string TimeSpanMinutePlural {
            get {
                return ResourceManager.GetString("TimeSpanMinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 minutes.
        /// </summary>
        public static string TimeSpanMinuteZero {
            get {
                return ResourceManager.GetString("TimeSpanMinuteZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # mois.
        /// </summary>
        public static string TimeSpanMonth {
            get {
                return ResourceManager.GetString("TimeSpanMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # mois.
        /// </summary>
        public static string TimeSpanMonthPlural {
            get {
                return ResourceManager.GetString("TimeSpanMonthPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 mois.
        /// </summary>
        public static string TimeSpanMonthZero {
            get {
                return ResourceManager.GetString("TimeSpanMonthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # seconde.
        /// </summary>
        public static string TimeSpanSecond {
            get {
                return ResourceManager.GetString("TimeSpanSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # secondes.
        /// </summary>
        public static string TimeSpanSecondPlural {
            get {
                return ResourceManager.GetString("TimeSpanSecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 seconde.
        /// </summary>
        public static string TimeSpanSecondZero {
            get {
                return ResourceManager.GetString("TimeSpanSecondZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # semaine.
        /// </summary>
        public static string TimeSpanWeek {
            get {
                return ResourceManager.GetString("TimeSpanWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # semaines.
        /// </summary>
        public static string TimeSpanWeekPlural {
            get {
                return ResourceManager.GetString("TimeSpanWeekPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 semaine.
        /// </summary>
        public static string TimeSpanWeekZero {
            get {
                return ResourceManager.GetString("TimeSpanWeekZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # année.
        /// </summary>
        public static string TimeSpanYear {
            get {
                return ResourceManager.GetString("TimeSpanYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # ans.
        /// </summary>
        public static string TimeSpanYearPlural {
            get {
                return ResourceManager.GetString("TimeSpanYearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 an.
        /// </summary>
        public static string TimeSpanYearZero {
            get {
                return ResourceManager.GetString("TimeSpanYearZero", resourceCulture);
            }
        }
    }
}
