//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Humanizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumHumanizeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumHumanizeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Humanizer.Resources.EnumHumanizeResources", typeof(EnumHumanizeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est.
        /// </summary>
        public static string BinaryOperatorIs {
            get {
                return ResourceManager.GetString("BinaryOperatorIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;est pas.
        /// </summary>
        public static string BinaryOperatorIsNot {
            get {
                return ResourceManager.GetString("BinaryOperatorIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egal à.
        /// </summary>
        public static string ComparableOperatorEqualsTo {
            get {
                return ResourceManager.GetString("ComparableOperatorEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supérieur ou égal à.
        /// </summary>
        public static string ComparableOperatorGreaterEqualThan {
            get {
                return ResourceManager.GetString("ComparableOperatorGreaterEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supérieur à.
        /// </summary>
        public static string ComparableOperatorGreaterThan {
            get {
                return ResourceManager.GetString("ComparableOperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inférieur ou égal à.
        /// </summary>
        public static string ComparableOperatorLessEqualThan {
            get {
                return ResourceManager.GetString("ComparableOperatorLessEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inférieur à.
        /// </summary>
        public static string ComparableOperatorLessThan {
            get {
                return ResourceManager.GetString("ComparableOperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différent de.
        /// </summary>
        public static string ComparableOperatorNotEqualsTo {
            get {
                return ResourceManager.GetString("ComparableOperatorNotEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egal à.
        /// </summary>
        public static string ComplexComparableOperatorEqualsTo {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supérieur ou égal à.
        /// </summary>
        public static string ComplexComparableOperatorGreaterEqualThan {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorGreaterEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supérieur à.
        /// </summary>
        public static string ComplexComparableOperatorGreaterThan {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est entre.
        /// </summary>
        public static string ComplexComparableOperatorIsBetween {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorIsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;est pas entre.
        /// </summary>
        public static string ComplexComparableOperatorIsNotBetween {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorIsNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inférieur ou égal à.
        /// </summary>
        public static string ComplexComparableOperatorLessEqualThan {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorLessEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inférieur à.
        /// </summary>
        public static string ComplexComparableOperatorLessThan {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différent de.
        /// </summary>
        public static string ComplexComparableOperatorNotEqualsTo {
            get {
                return ResourceManager.GetString("ComplexComparableOperatorNotEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue calendrier.
        /// </summary>
        public static string DisplayModeCalendar {
            get {
                return ResourceManager.GetString("DisplayModeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue graphique.
        /// </summary>
        public static string DisplayModeChart {
            get {
                return ResourceManager.GetString("DisplayModeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue jour.
        /// </summary>
        public static string DisplayModeDay {
            get {
                return ResourceManager.GetString("DisplayModeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue détailée.
        /// </summary>
        public static string DisplayModeDetailled {
            get {
                return ResourceManager.GetString("DisplayModeDetailled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue grille.
        /// </summary>
        public static string DisplayModeGrid {
            get {
                return ResourceManager.GetString("DisplayModeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue liste.
        /// </summary>
        public static string DisplayModeList {
            get {
                return ResourceManager.GetString("DisplayModeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue mois.
        /// </summary>
        public static string DisplayModeMonth {
            get {
                return ResourceManager.GetString("DisplayModeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue semaine.
        /// </summary>
        public static string DisplayModeWeek {
            get {
                return ResourceManager.GetString("DisplayModeWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue année.
        /// </summary>
        public static string DisplayModeYear {
            get {
                return ResourceManager.GetString("DisplayModeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octet.
        /// </summary>
        public static string FileSizeUnitByte {
            get {
                return ResourceManager.GetString("FileSizeUnitByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string FileSizeUnitByteAbbr {
            get {
                return ResourceManager.GetString("FileSizeUnitByteAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gigaoctet.
        /// </summary>
        public static string FileSizeUnitGigabyte {
            get {
                return ResourceManager.GetString("FileSizeUnitGigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go.
        /// </summary>
        public static string FileSizeUnitGigabyteAbbr {
            get {
                return ResourceManager.GetString("FileSizeUnitGigabyteAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilooctet.
        /// </summary>
        public static string FileSizeUnitKilobyte {
            get {
                return ResourceManager.GetString("FileSizeUnitKilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ko.
        /// </summary>
        public static string FileSizeUnitKilobyteAbbr {
            get {
                return ResourceManager.GetString("FileSizeUnitKilobyteAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megaoctet.
        /// </summary>
        public static string FileSizeUnitMegabyte {
            get {
                return ResourceManager.GetString("FileSizeUnitMegabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mo.
        /// </summary>
        public static string FileSizeUnitMegabyteAbbr {
            get {
                return ResourceManager.GetString("FileSizeUnitMegabyteAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to téraoctet.
        /// </summary>
        public static string FileSizeUnitTerabyte {
            get {
                return ResourceManager.GetString("FileSizeUnitTerabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string FileSizeUnitTerabyteAbbr {
            get {
                return ResourceManager.GetString("FileSizeUnitTerabyteAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avancé.
        /// </summary>
        public static string FilteringModeAdvanced {
            get {
                return ResourceManager.GetString("FilteringModeAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapide.
        /// </summary>
        public static string FilteringModeSpeed {
            get {
                return ResourceManager.GetString("FilteringModeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimètre.
        /// </summary>
        public static string LengthUnitCentimeter {
            get {
                return ResourceManager.GetString("LengthUnitCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string LengthUnitCentimeterAbbr {
            get {
                return ResourceManager.GetString("LengthUnitCentimeterAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to décamètre.
        /// </summary>
        public static string LengthUnitDecameter {
            get {
                return ResourceManager.GetString("LengthUnitDecameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dam.
        /// </summary>
        public static string LengthUnitDecameterAbbr {
            get {
                return ResourceManager.GetString("LengthUnitDecameterAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to décimètre.
        /// </summary>
        public static string LengthUnitDecimeter {
            get {
                return ResourceManager.GetString("LengthUnitDecimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dm.
        /// </summary>
        public static string LengthUnitDecimeterAbbr {
            get {
                return ResourceManager.GetString("LengthUnitDecimeterAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hectomètre.
        /// </summary>
        public static string LengthUnitHectometer {
            get {
                return ResourceManager.GetString("LengthUnitHectometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hm.
        /// </summary>
        public static string LengthUnitHectometerAbbr {
            get {
                return ResourceManager.GetString("LengthUnitHectometerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilomètre.
        /// </summary>
        public static string LengthUnitKilometer {
            get {
                return ResourceManager.GetString("LengthUnitKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string LengthUnitKilometerAbbr {
            get {
                return ResourceManager.GetString("LengthUnitKilometerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mètre.
        /// </summary>
        public static string LengthUnitMeter {
            get {
                return ResourceManager.GetString("LengthUnitMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string LengthUnitMeterAbbr {
            get {
                return ResourceManager.GetString("LengthUnitMeterAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to micromètre.
        /// </summary>
        public static string LengthUnitMicrometer {
            get {
                return ResourceManager.GetString("LengthUnitMicrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μm.
        /// </summary>
        public static string LengthUnitMicrometerAbbr {
            get {
                return ResourceManager.GetString("LengthUnitMicrometerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millimètre.
        /// </summary>
        public static string LengthUnitMillimeter {
            get {
                return ResourceManager.GetString("LengthUnitMillimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string LengthUnitMillimeterAbbr {
            get {
                return ResourceManager.GetString("LengthUnitMillimeterAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nanomètre.
        /// </summary>
        public static string LengthUnitNanometer {
            get {
                return ResourceManager.GetString("LengthUnitNanometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nm.
        /// </summary>
        public static string LengthUnitNanometerAbbr {
            get {
                return ResourceManager.GetString("LengthUnitNanometerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et.
        /// </summary>
        public static string LogicalOperatorAnd {
            get {
                return ResourceManager.GetString("LogicalOperatorAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou.
        /// </summary>
        public static string LogicalOperatorOr {
            get {
                return ResourceManager.GetString("LogicalOperatorOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centigramme.
        /// </summary>
        public static string MassUnitCentigram {
            get {
                return ResourceManager.GetString("MassUnitCentigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cg.
        /// </summary>
        public static string MassUnitCentigramAbbr {
            get {
                return ResourceManager.GetString("MassUnitCentigramAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to décagramme.
        /// </summary>
        public static string MassUnitDecagram {
            get {
                return ResourceManager.GetString("MassUnitDecagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dag.
        /// </summary>
        public static string MassUnitDecagramAbbr {
            get {
                return ResourceManager.GetString("MassUnitDecagramAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to décigramme.
        /// </summary>
        public static string MassUnitDecigram {
            get {
                return ResourceManager.GetString("MassUnitDecigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dg.
        /// </summary>
        public static string MassUnitDecigramAbbr {
            get {
                return ResourceManager.GetString("MassUnitDecigramAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gramme.
        /// </summary>
        public static string MassUnitGram {
            get {
                return ResourceManager.GetString("MassUnitGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string MassUnitGramAbbr {
            get {
                return ResourceManager.GetString("MassUnitGramAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hectogramme.
        /// </summary>
        public static string MassUnitHectogram {
            get {
                return ResourceManager.GetString("MassUnitHectogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hg.
        /// </summary>
        public static string MassUnitHectogramAbbr {
            get {
                return ResourceManager.GetString("MassUnitHectogramAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilogramme.
        /// </summary>
        public static string MassUnitKilogram {
            get {
                return ResourceManager.GetString("MassUnitKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string MassUnitKilogramAbbr {
            get {
                return ResourceManager.GetString("MassUnitKilogramAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milligramme.
        /// </summary>
        public static string MassUnitMilligram {
            get {
                return ResourceManager.GetString("MassUnitMilligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string MassUnitMilligramAbbr {
            get {
                return ResourceManager.GetString("MassUnitMilligramAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contient.
        /// </summary>
        public static string StringOperatorContains {
            get {
                return ResourceManager.GetString("StringOperatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se termine par.
        /// </summary>
        public static string StringOperatorEndsWith {
            get {
                return ResourceManager.GetString("StringOperatorEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est.
        /// </summary>
        public static string StringOperatorIs {
            get {
                return ResourceManager.GetString("StringOperatorIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;est pas.
        /// </summary>
        public static string StringOperatorIsNot {
            get {
                return ResourceManager.GetString("StringOperatorIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commence par.
        /// </summary>
        public static string StringOperatorStartsWith {
            get {
                return ResourceManager.GetString("StringOperatorStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour(s).
        /// </summary>
        public static string TimeUnitDay {
            get {
                return ResourceManager.GetString("TimeUnitDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j.
        /// </summary>
        public static string TimeUnitDayAbbr {
            get {
                return ResourceManager.GetString("TimeUnitDayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure(s).
        /// </summary>
        public static string TimeUnitHour {
            get {
                return ResourceManager.GetString("TimeUnitHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string TimeUnitHourAbbr {
            get {
                return ResourceManager.GetString("TimeUnitHourAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconde(s).
        /// </summary>
        public static string TimeUnitMillisecond {
            get {
                return ResourceManager.GetString("TimeUnitMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milli.
        /// </summary>
        public static string TimeUnitMillisecondAbbr {
            get {
                return ResourceManager.GetString("TimeUnitMillisecondAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute(s).
        /// </summary>
        public static string TimeUnitMinute {
            get {
                return ResourceManager.GetString("TimeUnitMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string TimeUnitMinuteAbbr {
            get {
                return ResourceManager.GetString("TimeUnitMinuteAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mois.
        /// </summary>
        public static string TimeUnitMonth {
            get {
                return ResourceManager.GetString("TimeUnitMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string TimeUnitMonthAbbr {
            get {
                return ResourceManager.GetString("TimeUnitMonthAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconde(s).
        /// </summary>
        public static string TimeUnitSecond {
            get {
                return ResourceManager.GetString("TimeUnitSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string TimeUnitSecondAbbr {
            get {
                return ResourceManager.GetString("TimeUnitSecondAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaines(s).
        /// </summary>
        public static string TimeUnitWeek {
            get {
                return ResourceManager.GetString("TimeUnitWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sem.
        /// </summary>
        public static string TimeUnitWeekAbbr {
            get {
                return ResourceManager.GetString("TimeUnitWeekAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année(s).
        /// </summary>
        public static string TimeUnitYear {
            get {
                return ResourceManager.GetString("TimeUnitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string TimeUnitYearAbbr {
            get {
                return ResourceManager.GetString("TimeUnitYearAbbr", resourceCulture);
            }
        }
    }
}
