//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Demo.Resources.DemoResources", typeof(DemoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer OnClick.
        /// </summary>
        internal static string ActivateOnClick {
            get {
                return ResourceManager.GetString("ActivateOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer OnClose.
        /// </summary>
        internal static string ActivateOnClose {
            get {
                return ResourceManager.GetString("ActivateOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extérieur.
        /// </summary>
        internal static string AwayTeam {
            get {
                return ResourceManager.GetString("AwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bas.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutons.
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition des boutons.
        /// </summary>
        internal static string ButtonsLayout {
            get {
                return ResourceManager.GetString("ButtonsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position des boutons.
        /// </summary>
        internal static string ButtonsPosition {
            get {
                return ResourceManager.GetString("ButtonsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple intervalles de date.
        /// </summary>
        internal static string CalendarSelectionModeMultipleRange {
            get {
                return ResourceManager.GetString("CalendarSelectionModeMultipleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string CalendarSelectionModeNone {
            get {
                return ResourceManager.GetString("CalendarSelectionModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date unique.
        /// </summary>
        internal static string CalendarSelectionModeSingleDate {
            get {
                return ResourceManager.GetString("CalendarSelectionModeSingleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalle de dates.
        /// </summary>
        internal static string CalendarSelectionModeSingleRange {
            get {
                return ResourceManager.GetString("CalendarSelectionModeSingleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réordonner.
        /// </summary>
        internal static string CanUserReorderColumns {
            get {
                return ResourceManager.GetString("CanUserReorderColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionner.
        /// </summary>
        internal static string CanUserResizeColumns {
            get {
                return ResourceManager.GetString("CanUserResizeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier.
        /// </summary>
        internal static string CanUserSortColumns {
            get {
                return ResourceManager.GetString("CanUserSortColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocher.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratégie de fermeture.
        /// </summary>
        internal static string ClosingStrategy {
            get {
                return ResourceManager.GetString("ClosingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refermer.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangulaire.
        /// </summary>
        internal static string ColorSpectrumShapeBox {
            get {
                return ResourceManager.GetString("ColorSpectrumShapeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulaire.
        /// </summary>
        internal static string ColorSpectrumShapeRing {
            get {
                return ResourceManager.GetString("ColorSpectrumShapeRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonnes.
        /// </summary>
        internal static string Columnar {
            get {
                return ResourceManager.GetString("Columnar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur des entêtes de colonne.
        /// </summary>
        internal static string ColumnHeaderHeight {
            get {
                return ResourceManager.GetString("ColumnHeaderHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur du volet fermé.
        /// </summary>
        internal static string CompactPaneLength {
            get {
                return ResourceManager.GetString("CompactPaneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composantes.
        /// </summary>
        internal static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôles.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes.
        /// </summary>
        internal static string DataGridGridLinesVisibilityAll {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string DataGridGridLinesVisibilityHorizontal {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        internal static string DataGridGridLinesVisibilityNone {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string DataGridGridLinesVisibilityVertical {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        internal static string DataGridHeadersVisibilityAll {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonne.
        /// </summary>
        internal static string DataGridHeadersVisibilityColumn {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string DataGridHeadersVisibilityNone {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        internal static string DataGridHeadersVisibilityRow {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etendu.
        /// </summary>
        internal static string DataGridSelectionModeExtended {
            get {
                return ResourceManager.GetString("DataGridSelectionModeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string DataGridSelectionModeSingle {
            get {
                return ResourceManager.GetString("DataGridSelectionModeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendredi.
        /// </summary>
        internal static string DayOfWeekFriday {
            get {
                return ResourceManager.GetString("DayOfWeekFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lundi.
        /// </summary>
        internal static string DayOfWeekMonday {
            get {
                return ResourceManager.GetString("DayOfWeekMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samedi.
        /// </summary>
        internal static string DayOfWeekSaturday {
            get {
                return ResourceManager.GetString("DayOfWeekSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimanche.
        /// </summary>
        internal static string DayOfWeekSunday {
            get {
                return ResourceManager.GetString("DayOfWeekSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeudi.
        /// </summary>
        internal static string DayOfWeekThursday {
            get {
                return ResourceManager.GetString("DayOfWeekThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mardi.
        /// </summary>
        internal static string DayOfWeekTuesday {
            get {
                return ResourceManager.GetString("DayOfWeekTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercredi.
        /// </summary>
        internal static string DayOfWeekWednesday {
            get {
                return ResourceManager.GetString("DayOfWeekWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée d&apos;affichage.
        /// </summary>
        internal static string DisplayDuration {
            get {
                return ResourceManager.GetString("DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode d&apos;affichage.
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;affichage.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Dots {
            get {
                return ResourceManager.GetString("Dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bas.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position du curseur.
        /// </summary>
        internal static string DropDownPlacement {
            get {
                return ResourceManager.GetString("DropDownPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est editable.
        /// </summary>
        internal static string Editable {
            get {
                return ResourceManager.GetString("Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs invalide.
        /// </summary>
        internal static string ErrorOnFieldMessage {
            get {
                return ResourceManager.GetString("ErrorOnFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flottant.
        /// </summary>
        internal static string Floating {
            get {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif au survol.
        /// </summary>
        internal static string FreezeOnMouseEnter {
            get {
                return ResourceManager.GetString("FreezeOnMouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les lignes.
        /// </summary>
        internal static string GridLinesVisibility {
            get {
                return ResourceManager.GetString("GridLinesVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aiguilles.
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entêtes.
        /// </summary>
        internal static string HeadersVisibility {
            get {
                return ResourceManager.GetString("HeadersVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicile.
        /// </summary>
        internal static string HomeTeam {
            get {
                return ResourceManager.GetString("HomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position de l&apos;icône.
        /// </summary>
        internal static string IconLayout {
            get {
                return ResourceManager.GetString("IconLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icônes.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les variations.
        /// </summary>
        internal static string IsAccentColorsVisible {
            get {
                return ResourceManager.GetString("IsAccentColorsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la transparence.
        /// </summary>
        internal static string IsAlphaVisible {
            get {
                return ResourceManager.GetString("IsAlphaVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher TSV.
        /// </summary>
        internal static string IsColorModelVisible {
            get {
                return ResourceManager.GetString("IsColorModelVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;aperçu.
        /// </summary>
        internal static string IsColorPreviewVisible {
            get {
                return ResourceManager.GetString("IsColorPreviewVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la saturation.
        /// </summary>
        internal static string IsColorSpectrumSliderVisible {
            get {
                return ResourceManager.GetString("IsColorSpectrumSliderVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverser la direction.
        /// </summary>
        internal static string IsDirectionReversed {
            get {
                return ResourceManager.GetString("IsDirectionReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;hexa.
        /// </summary>
        internal static string IsHexInputVisible {
            get {
                return ResourceManager.GetString("IsHexInputVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est infini.
        /// </summary>
        internal static string IsIndeterminate {
            get {
                return ResourceManager.GetString("IsIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volet ouvert.
        /// </summary>
        internal static string IsPaneOpen {
            get {
                return ResourceManager.GetString("IsPaneOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est un mot de passe.
        /// </summary>
        internal static string IsPassword {
            get {
                return ResourceManager.GetString("IsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est rond.
        /// </summary>
        internal static string IsRounded {
            get {
                return ResourceManager.GetString("IsRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est fluide.
        /// </summary>
        internal static string IsSmooth {
            get {
                return ResourceManager.GetString("IsSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrondir la valeur.
        /// </summary>
        internal static string IsSnapToTickEnabled {
            get {
                return ResourceManager.GetString("IsSnapToTickEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauche.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lignes.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure courante.
        /// </summary>
        internal static string LiveUpdate {
            get {
                return ResourceManager.GetString("LiveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eléments maximum.
        /// </summary>
        internal static string MaxItems {
            get {
                return ResourceManager.GetString("MaxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous venez de cliquer sur la notification &apos;{0}&apos;.
        /// </summary>
        internal static string NotificationClickMessage {
            get {
                return ResourceManager.GetString("NotificationClickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La notification a été fermée.
        /// </summary>
        internal static string NotificationClosedMessage {
            get {
                return ResourceManager.GetString("NotificationClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décalage horizontal.
        /// </summary>
        internal static string OffsetX {
            get {
                return ResourceManager.GetString("OffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décalage vertical.
        /// </summary>
        internal static string OffsetY {
            get {
                return ResourceManager.GetString("OffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacité.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur du volet ouvert.
        /// </summary>
        internal static string OpenPaneLength {
            get {
                return ResourceManager.GetString("OpenPaneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string OrientationHorizontal {
            get {
                return ResourceManager.GetString("OrientationHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string OrientationVertical {
            get {
                return ResourceManager.GetString("OrientationVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        internal static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette - Colonnes.
        /// </summary>
        internal static string PaletteColumnCount {
            get {
                return ResourceManager.GetString("PaletteColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position de la popup.
        /// </summary>
        internal static string PlacementFlyout {
            get {
                return ResourceManager.GetString("PlacementFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préfixe.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aléatoire.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aléatoire.
        /// </summary>
        internal static string Randomize {
            get {
                return ResourceManager.GetString("Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture seule.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitre.
        /// </summary>
        internal static string Referee {
            get {
                return ResourceManager.GetString("Referee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droite.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur des entêtes de ligne.
        /// </summary>
        internal static string RowHeaderWidth {
            get {
                return ResourceManager.GetString("RowHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur de ligne.
        /// </summary>
        internal static string RowHeight {
            get {
                return ResourceManager.GetString("RowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondes.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode de sélection.
        /// </summary>
        internal static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forme.
        /// </summary>
        internal static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le fond.
        /// </summary>
        internal static string ShowBackground {
            get {
                return ResourceManager.GetString("ShowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les boutons.
        /// </summary>
        internal static string ShowButtons {
            get {
                return ResourceManager.GetString("ShowButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection de la cellule.
        /// </summary>
        internal static string ShowCellSelection {
            get {
                return ResourceManager.GetString("ShowCellSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le bouton &quot;Effacer&quot;.
        /// </summary>
        internal static string ShowClearButton {
            get {
                return ResourceManager.GetString("ShowClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le jour.
        /// </summary>
        internal static string ShowDay {
            get {
                return ResourceManager.GetString("ShowDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher une erreur.
        /// </summary>
        internal static string ShowError {
            get {
                return ResourceManager.GetString("ShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le mois.
        /// </summary>
        internal static string ShowMonth {
            get {
                return ResourceManager.GetString("ShowMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la sélection.
        /// </summary>
        internal static string ShowSelection {
            get {
                return ResourceManager.GetString("ShowSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la valeur.
        /// </summary>
        internal static string ShowValueOnMouseOver {
            get {
                return ResourceManager.GetString("ShowValueOnMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;année.
        /// </summary>
        internal static string ShowYear {
            get {
                return ResourceManager.GetString("ShowYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectre.
        /// </summary>
        internal static string Spectrum {
            get {
                return ResourceManager.GetString("Spectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffixe.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverser les boutons.
        /// </summary>
        internal static string SwitchButtons {
            get {
                return ResourceManager.GetString("SwitchButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onglets.
        /// </summary>
        internal static string Tabs {
            get {
                return ResourceManager.GetString("Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fréquence des graduations.
        /// </summary>
        internal static string TickFrequency {
            get {
                return ResourceManager.GetString("TickFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur des graduations.
        /// </summary>
        internal static string TickLength {
            get {
                return ResourceManager.GetString("TickLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode de graduation.
        /// </summary>
        internal static string TickMode {
            get {
                return ResourceManager.GetString("TickMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux.
        /// </summary>
        internal static string TickModeBoth {
            get {
                return ResourceManager.GetString("TickModeBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation.
        /// </summary>
        internal static string TickModeTick {
            get {
                return ResourceManager.GetString("TickModeTick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs.
        /// </summary>
        internal static string TickModeValues {
            get {
                return ResourceManager.GetString("TickModeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement des graduations.
        /// </summary>
        internal static string TickPlacement {
            get {
                return ResourceManager.GetString("TickPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bas ou Droite.
        /// </summary>
        internal static string TickPlacementBottomRight {
            get {
                return ResourceManager.GetString("TickPlacementBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string TickPlacementNone {
            get {
                return ResourceManager.GetString("TickPlacementNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux.
        /// </summary>
        internal static string TickPlacementOutside {
            get {
                return ResourceManager.GetString("TickPlacementOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haut ou Gauche.
        /// </summary>
        internal static string TickPlacementTopLeft {
            get {
                return ResourceManager.GetString("TickPlacementTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduations.
        /// </summary>
        internal static string Ticks {
            get {
                return ResourceManager.GetString("Ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatique.
        /// </summary>
        internal static string ToastClosingStrategyAutoClose {
            get {
                return ResourceManager.GetString("ToastClosingStrategyAutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux.
        /// </summary>
        internal static string ToastClosingStrategyBoth {
            get {
                return ResourceManager.GetString("ToastClosingStrategyBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton.
        /// </summary>
        internal static string ToastClosingStrategyCloseButton {
            get {
                return ResourceManager.GetString("ToastClosingStrategyCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        internal static string ToastClosingStrategyNone {
            get {
                return ResourceManager.GetString("ToastClosingStrategyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas au centre.
        /// </summary>
        internal static string ToasterPositionBottomCenter {
            get {
                return ResourceManager.GetString("ToasterPositionBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas à gauche.
        /// </summary>
        internal static string ToasterPositionBottomLeft {
            get {
                return ResourceManager.GetString("ToasterPositionBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas à droite.
        /// </summary>
        internal static string ToasterPositionBottomRight {
            get {
                return ResourceManager.GetString("ToasterPositionBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut au centre.
        /// </summary>
        internal static string ToasterPositionTopCenter {
            get {
                return ResourceManager.GetString("ToasterPositionTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut à gauche.
        /// </summary>
        internal static string ToasterPositionTopLeft {
            get {
                return ResourceManager.GetString("ToasterPositionTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut à droite.
        /// </summary>
        internal static string ToasterPositionTopRight {
            get {
                return ResourceManager.GetString("ToasterPositionTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur.
        /// </summary>
        internal static string ToastWidth {
            get {
                return ResourceManager.GetString("ToastWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip.
        /// </summary>
        internal static string ToolTip {
            get {
                return ResourceManager.GetString("ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haut.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décocher.
        /// </summary>
        internal static string Uncheck {
            get {
                return ResourceManager.GetString("Uncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte affiché sous le contrôle.
        /// </summary>
        internal static string UnderText {
            get {
                return ResourceManager.GetString("UnderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniforme.
        /// </summary>
        internal static string Uniform {
            get {
                return ResourceManager.GetString("Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haut.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne alternée.
        /// </summary>
        internal static string UseAlternateRowBackground {
            get {
                return ResourceManager.GetString("UseAlternateRowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer l&apos;overlay.
        /// </summary>
        internal static string UseOverlay {
            get {
                return ResourceManager.GetString("UseOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les secondes.
        /// </summary>
        internal static string UseSeconds {
            get {
                return ResourceManager.GetString("UseSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser le filigrane.
        /// </summary>
        internal static string UseWatermark {
            get {
                return ResourceManager.GetString("UseWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position de la valeur.
        /// </summary>
        internal static string ValuePosition {
            get {
                return ResourceManager.GetString("ValuePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu.
        /// </summary>
        internal static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filigrane.
        /// </summary>
        internal static string Watermark {
            get {
                return ResourceManager.GetString("Watermark", resourceCulture);
            }
        }
    }
}
