//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Utilities.Generator.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Utilities.Generator.Extensions.Resources.NamesResources", typeof(NamesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jade;Louise;Emma;Alice;Ambre;Lina;Rose;Chloé;Mia;Léa;Anna;Mila;Julia;Romy;Lou;Inès;Léna;Agathe;Juliette;Inaya;Nina;Zoé;Jeanne;Léonie;Iris;Eva;Charlie;Lola;Adèle;Victoire;Manon;Luna;Camille;Romane;Lucie;Margaux;Olivia;Victoria;Alix;Louna;Mya;Sofia;Charlotte;Sarah;Giulia;Lya;Margot;Nour;Lyana;Capucine;Clémence;Théa;Elena;Alba;Emy;Clara;Lana;Aya;Lyna;Yasmine;Gabrielle;Alya;Alicia;Roxane;Zélie;Lise;Lily;Léana;Livia;Mathilde;Maya;Valentine;Anaïs;Apolline;Lila;Thaïs;Maëlys;Assia;Ava;Héloïse;Joy;Alma;Lilou;Maria;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleFirstNames {
            get {
                return ResourceManager.GetString("FemaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martin;Bernard;Thomas;Petit;Robert;Richard;Durand;Dubois;Moreau;Laurent;Simon;Michel;Lefebvre;Leroy;Roux;David;Bertrand;Morel;Fournier;Girard;Bonnet;Dupont;Lambert;Fontaine;Rousseau;Vincent;Muller;Lefevre;Faure;Andre;Mercier;Blanc;Guerin;Boyer;Garnier;Chevalier;Francois;Legrand;Gauthier;Garcia;Perrin;Robin;Clement;Morin;Nicolas;Henry;Roussel;Mathieu;Gautier;Masson;Marchand;Duval;Denis;Dumont;Marie;Lemaire;Noel;Meyer;Dufour;Meunier;Brun;Blanchard;Giraud;Joly;Riviere;Lucas;Brunet;Gaillard;Barbier;Arnaud;Marti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alain;Alan;Alphonse;Aristide;Armand;Benjamin;Bernard;Charles;Christian;Christophe;Claude;Colin;Damien;Daniel;David;Dominique;Éric;Eugène;Félix;François;Georges;Gérard;Guillaume;Henri;Hervé;Jacques;Jean;Jérémy;Joël;Julien;Luc;Marc;Marcel;Matthieu;Maurice;Michel;Michaël;Nicolas;Noël;Norbert;Olivier;Patrick;Philippe;Quentin;Raoul;Renaud;René;Richard;Robert;Roger;Sébastien;Stéphane;Thibaut;Thierry;Vincent;Xavier;Yves;Yvan;Léo;Gabriel;Raphaël;Arthur;Louis;Jules;Adam;Maël;Lucas;Hugo;Noah;Liam;Gabin;Sacha;Paul;Nat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleFirstNames {
            get {
                return ResourceManager.GetString("MaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.;Mme.;Mlle.;Dr..
        /// </summary>
        internal static string Prefixes {
            get {
                return ResourceManager.GetString("Prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jr.;Sr..
        /// </summary>
        internal static string Suffixes {
            get {
                return ResourceManager.GetString("Suffixes", resourceCulture);
            }
        }
    }
}
