name: Manual - Tag Projects

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run - Only show what would be tagged without creating tags'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      force_all:
        description: 'Force tag all projects regardless of changes'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    uses: sandre58/MyWorkflows/.github/workflows/release.yml@main
    with:
      dry-run: ${{ inputs.dry_run }}
